### PR TITLE
Feature delete trainee

### PR DESCRIPTION
**Pull request by christian-dawson**

### CODE REVIEW

**Comment by nemecbe** [comment]
Hi, I worked on this project a while ago and am curious why this branch was merged directly into master instead of going into develop first. @vijaysadanani maybe you have some insights? If I remember correctly, this request was closed because it needed to go into the develop branch first.

Thanks,

Benjamin Nemec
Former Revature Trainee and current Associate on a client project

**Comment by vijaysadanani** [comment]
Hey Benjamin,

Apologies if the notification disturbed you in anyway. It was an accident
to have requested the merge into master (I believe I don’t have permissions
to merge into master anyways).

Sorry for any inconvenience this may have caused.

Regards,

Vijay Sadanani

**Comment by myette** [comment]
Have no fear, our batch’s MVP is here!!!

Good catch, Ben.

**Comment by nemecbe** [comment]
@vijaysadanani  No worries, although you may want to double check your privileges, because it looks like this did merge directly into master. Best of luck!

**Comment by vijaysadanani** [comment]
Yeah Ill notify the appropriate people, thanks for the notification! I was
able to revert the changes made via the pull request.

Regards,

Vijay Sadanani

**Pull request merged**
