### PR TITLE
View individual qc results

### PR DESCRIPTION
**Pull request by RoyalProfessor**
View Individual QC results for specific week finished.

### CODE REVIEW

**Review by rlayneorr — CHANGES_REQUESTED** [review]
Remove console logs

**Review by rlayneorr — CHANGES_REQUESTED** [review]
Remove console logs

**Comment by rlayneorr** [comment]
Remove even more console logs

**Comment by RoyalProfessor** [comment]
Alright how about now?

**Review by rlayneorr — APPROVED** [review]

**Pull request merged**
